apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app.kubernetes.io/name: myapp
  namespace: default
spec:
  containers:
  - name: myapp
    image: nginx
    ports:
      - containerPort: 8080