apiVersion: v1
kind: Pod
metadata:
  name: controller
  namespace: default
spec:
  serviceAccountName: controller
  containers:
  - name: controller
    image: docker.io/chahatyadav1/label-controller:v1.0.0
    ports:
      - containerPort: 8000