apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    "inject-sidecar": 'true'
  namespace: default
spec:
  containers:
  - name: logger1
    image: alpine
    ports:
      - containerPort: 80
